language: scala
scala:
- 2.11.5
after_success:
- sh "$TRAVIS_BUILD_DIR/.travis.credentials.sh" && sbt publish
env:
  global:
  - secure: rI0yiqoisNVKhH/ofJ00Ymj47Uw4FYvxhiNmCv5LObfu6dQQohaMi9BAVzpr+aVvBeXfWT5As9giTuDZfcxkHoXXMM0VIEgp5XpLxRFDOJBmvgagJqN/tM22yU3aDexQm/ORBpETLnYtvbazbo6q7fYT+pfc8HEtu8BfbpLe4ro=
  - secure: f2iy9eo7ZQThWGNW1kCllTEFaGi9EuiJKYnRe6SsbXZjmxeo8Q+KvPvbqOjkvdH43krFySnrF1VO/fdhDMcP2XmnCkyyX37K/c/iOZSWoyCydYeydM0YgNoUpoxiFC9WCgffSWI4q1Tn0RsC+yzXrysXf6/ii4S8SBuRv4yBTHA=
